[tool.poetry]
name = "pythonhw2"
version = "0.1.0"
description = ""
authors = ["jasonschreib <jwschreiber1@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.3"
numpy = "^1.21.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
